server:
  port: 8010
spring:
  profiles:
    active: user
  application:
    name: microservice-consumer-movie       # 指定注册到 Eureka Server 上的应用名称，会被自动转换为大写

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true                 # 将自己的 IP 注册到 Eureka Server

logging:
  level:
    com.mawen.movie.feignclient.UserFeignClient: DEBUG # 将Feign接口的日志级别设置成DEBUG，因为Feign的Logger.LEVEL只会DEBUG做出响应