server:
  port: @server.port@
spring:
  application:
    name: provider-nacos
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource: # 指定数据源
    platform: h2                  # 指定数据源类型
    schema: classpath:schema.sql  # 指定h2数据库的建表脚本
    data: classpath:data.sql      # 指定h2数据库的数据脚本
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
logging: # 配置日志级别，让hibernate打印执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

---
spring:
  profiles:
    active: docker
  cloud:
    nacos:
      discovery:
        server-addr: @docker.service.discovery.name@:8848

