server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mawen12/config-repo # 配置Git仓库的地址
        health:
          repositories:
            a-foo:
              label: config-label-v2.0
              name: microservice-foo
              profiles: dev

logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: DEBUG
