server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul-filter
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  PreRequestLogFilter:
    pre:
      disable: false # zuul.<SimpleClassName>.<filterType>.disable 设置过滤器是否禁用
