version: "2.1"

services:
  consul:
    image: consul:1.15.0
    restart: always
    ports:
      - "8500:8500"
      - "8600:8600"
    mem_limit: 1g
    mem_reservation: 1g
  provider-consul:
    image: mawen/hoxton.provider-user-consul:1.0-SNAPSHOT
    ports:
      - "8000:8000"
      - "5005:5005"
    depends_on:
      - consul
    mem_limit: 1g
    mem_reservation: 1g
  consumer-consul:
    image: mawen/hoxton.consumer-user-consul:1.0-SNAPSHOT
    ports:
      - "8010:8010"
      - "15005:5005"
    depends_on:
      - consul
    mem_limit: 1g
    mem_reservation: 1g
