server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 600000  # 上传大文件得将超时时间设置长一些
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000