server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul-fallback
zuul:
  routes:
    microservice-provider-user: /user/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.netflix: DEBUG