server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mawen12/config-repo # 配置Git仓库的地址
security:
  basic:
    enabled: true
  user:
    name: user
    password: password123