server:
  port: 8761
eureka:
  client:
    registerWithEureka: false                     # 不将自己注册到 Eureka Server(本身就是Eureka Server)
    fetchRegistry: false                          # 不从其他节点同步注册信息(单节点)
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server 交互地址

security:
  basic:
    enabled: true     # 开启基于HTTP BASIC的认证
  user:
    name: mawen       # 配置登录的账号是user
    password: 123456  # 配置登录的密码是123456
