server:
  port: 8020
spring:
  profiles:
    active: user
  application:
    name: microservice-consumer-movie-feign-fallback-hystrix-stream   # 指定注册到 Eureka Server 上的应用名称，会被自动转换为大写

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true                       # 将自己的 IP 注册到 Eureka Server