server:
  port: @server.port@
spring:
  application:
    name: consumer-nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

---
spring:
  profiles:
    active: docker
  cloud:
    nacos:
      discovery:
        server-addr: @docker.service.discovery.name@:8848



