server:
  port: 8000
spring:
  application:
    name: microservice-provider-user    # 指定注册到 Eureka Server 上的应用名称，会被自动转换为大写
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                     # 指定数据源
    platform: h2                  # 指定数据源类型
    schema: classpath:schema.sql  # 指定h2数据库的建表脚本
    data: classpath:data.sql      # 指定h2数据库的数据脚本
logging:                          # 配置日志级别，让hibernate打印执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

info:                                           # 自定义info断点信息
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

eureka:
  client:
    serviceUrl:
      defaultZone: http://mawen:123456@localhost:8761/eureka/ # 注册到需要用户认证的 Eureka Server
#      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true             # 将自己的 IP 注册到 Eureka Server
    metadata-map:
      my-metadata: 我自定义的元数据       # 自定义的元数据，key/value都可以随便写